### ISSUE TITLE
Oct 27 - Nov 3

### ISSUE THREAD

**Issue by gregtatum** [gregtatum/z-index-devtool#52]
## Bria: Selected Node
- [ ] Get Mocha in source control
- [ ] Start writing tests for actions
## James: Tree Component
- [x] Finish renderItem
- [x] Implement Arrow
- [ ] Make it look purrty. (CSS)
## Wenny: Tree Component
- [x] Figure out how to store the reasons why a node is a stacking context
- [x] Create a new component to show them
- [x] Make sure it all works together.

**Comment by jreinlein** [comment]
Point of discussion for next meeting:

I started fixing up the HTML example files because their style was affecting the entire page (including the other pane of the split view; the tree itself), but then it got me thinking... 
IRL, will we be passing in the entire HTML/CSS of a page or would a user have to curate it slightly first?

Alternatively, is there a way to keep the CSS contained to a certain portion of the page? I tried `<style scoped>` but it wasn't successful.

**Comment by gregtatum** [comment]
In a real devtools situation we'd have a messaging system. Firefox uses a whole fancy complicated Remote Debugging Protocol that even has a spec: https://wiki.mozilla.org/Remote_Debugging_Protocol

For our cases we can could create a simple messaging system to pass messages between the z-index tool, and an iframe that loads the content. The API for this is the window.postMessage: https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

**Comment by gregtatum** [comment]
Web Extensions if you're not familiar is the cross-browser specification built off of Chrome's extension system. Firefox and other browsers have been implementing the API so that extensions can work across browsers. They have a messaging model that also features content scripts and background scripts: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_scripts

Web Extensions are interesting because they are a really nice way to write addons, but the security model for Web Extensions, and the old style add-ons (which is what our devtools uses) don't mix and match. It's probably easier and nicer to use Web Extensions, as when you use the old-style add-ons you get a huge amount of raw functionality, but it's a bit wild west in how it works.

**Comment by gregtatum** [comment]
Good job team!
