### ISSUE TITLE
Get the current stacking context when you switch back to Z-Index tab

### ISSUE THREAD

**Issue by bomsy** [gregtatum/z-index-devtool#88]
If we switch way from the z index tab and switch back, the stacking context tree is not updated.

STR
* Click the inspector tab
* update the web page
* switch back to the z index tab

AR
The stacking context tree is not updated

ER
The stacking context tree should be updated

**Comment by captainbrosset** [comment]
How about if there are markup mutations happening dynamically on the page even without switching to a different tab?
I guess the extension doesn't react to those either.

What about we just add a `MutationObserver` in the content script that listens for any kind of changes and updates the tree when they happen (probably will need throttling too because some pages animate stuff by changing the DOM very rapidly)?

This way, I don't think we would need to update the tree when the tab is selected again.

**Comment by bomsy** [comment]
We have a Mutation observer already and it watches and updates the app.

I think the issue here is when we switch away from the z-index  panel, and then change the DOM , the mutation observer picks up the change and sends a message to the panel but since its no longer open, it does not seem to receive the messages from the CS. This is just my theory :) Need to investigate more...

**Comment by captainbrosset** [comment]
Oh I see!

**Comment by bomsy** [comment]
So it works, i was just dumbly killing the observer when we move away from the tab.
